theme: jekyll-theme-hacker

baseurl: /gridka-school-2019-htcondor

show_downloads: true

collections:
  exercises:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: exercises
    values:
      layout: default

plugins:
  - jemoji

relative_links:
  enabled:     true
  collections: true
